/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardActivityRouteImport } from './routes/dashboard/activity'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardBountiesRouteImport } from './routes/dashboard/bounties'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAgentsIndexRouteImport } from './routes/dashboard/agents/index'
import { Route as DashboardAgentsNameRouteImport } from './routes/dashboard/agents/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBountiesRoute = DashboardBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsNameRoute = DashboardAgentsNameRouteImport.update({
  id: '/agents/$name',
  path: '/agents/$name',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bounties': typeof DashboardBountiesRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/$name': typeof DashboardAgentsNameRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bounties': typeof DashboardBountiesRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/agents/$name': typeof DashboardAgentsNameRoute
  '/dashboard/agents': typeof DashboardAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bounties': typeof DashboardBountiesRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/$name': typeof DashboardAgentsNameRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/authorize'
    | '/device'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/bounties'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/agents/$name'
    | '/dashboard/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/device'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/bounties'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/agents/$name'
    | '/dashboard/agents'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/authorize'
    | '/device'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/bounties'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/agents/$name'
    | '/dashboard/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bounties': {
      id: '/dashboard/bounties'
      path: '/bounties'
      fullPath: '/dashboard/bounties'
      preLoaderRoute: typeof DashboardBountiesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agents/': {
      id: '/dashboard/agents/'
      path: '/agents'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agents/$name': {
      id: '/dashboard/agents/$name'
      path: '/agents/$name'
      fullPath: '/dashboard/agents/$name'
      preLoaderRoute: typeof DashboardAgentsNameRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBountiesRoute: typeof DashboardBountiesRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAgentsNameRoute: typeof DashboardAgentsNameRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBountiesRoute: DashboardBountiesRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAgentsNameRoute: DashboardAgentsNameRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
